
# Constants
ACTION_LOAD_LLM = 1
ACTION_GENERATE_TEXT = 2
ACTION_UNLOAD_LLM = 3

STATUS_CODE_ERROR = 0
STATUS_CODE_SUCCESS = 1

# Model Ids List
MODEL_LLAMA_3DOT1_8B_INSTRUCT = "meta-llama/Llama-3.1-8B-Instruct"
MODEL_LLAMA_3DOT2_3B_INSTRUCT = "meta-llama/Llama-3.2-3B-Instruct"
MODEL_IDS = (MODEL_LLAMA_3DOT1_8B_INSTRUCT, MODEL_LLAMA_3DOT2_3B_INSTRUCT)