# ROS LLM Request Model
# LICENSE: Apache 2.0

int32 action
string model_id
string prompt

# Aditional model configuration
uint32 max_length 200
float32 temperature 0.7
uint32 top_k 50
float32 top_p 0.9

# Images for LVLMs
string[] images

uint8 ACTION_LOAD_MODEL     = 1
uint8 ACTION_GENERATE_TEXT  = 2
uint8 ACTION_UNLOAD_MODEL   = 3

---
# Response fields
int32 status_code
string status_message
string generated_text

uint8 STATUS_CODE_ERROR     = 0
uint8 STATUS_CODE_SUCCESS   = 1